#server:
#  port: 8084
#spring:
#  main:
#    allow-bean-definition-overriding: true
#  application:
#    name: config-client
#  config:
#    import: configserver:http://localhost:8080
#  security:
#    oauth2:
#      client:
#        registration:
#          client-server-oidc:
#            provider: authorizer
#            client-id: client-server-id
#            client-secret: secret
#            authorization-grant-type: authorization_code
#            redirect-uri: "http://127.0.0.1:8084/authorized"
#            client-name: client-server-oidc
#            scope: openid,profile,read,write
#        provider:
#          authorizer:
#            issuer-uri: http://localhost:9000


server:
  port: 8084
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: config-client
  config:
    import: configserver:http://localhost:8080
  security:
    oauth2:
      client:
        registration:
          client-server-oidc:
            provider: authorizer
            client-id: client-server-id
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid,profile,read,write
            client-name: client-server-oidc
        provider:
          authorizer:
            issuer-uri: "http://localhost:9000"
