server:
  port: 8082
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: config-client
  config:
    import: configserver:http://localhost:8080
  security:
    oauth2:
      client:
        registration:
          client-server-oidc:
            provider: spring
            client-id: client-server-id
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8080/login/oauth2/code/{registrationId}"
            scope: openid, profile
            client-name: client-server-oidc
        provider:
          spring:
            issuer-uri: http://localhost:8181
